POST http://localhost:8089/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxN2JlMGZhMzkwY2U2MDI5N2M1N2FlYiIsInVzZXJuYW1lIjoibmFjaG8iLCJpYXQiOjE2MzU4OTIwMTQsImV4cCI6MTYzNjQ5NjgxNH0.KGqY9i75-8cakmNbu-O4dA72z_8cOjmAVqVNAfhTZR4

{
  "content": "Suscríbete a @midudevaaaa",
  "important": true
}